package com.hanhan.test1.dao.mapperJava1;

import com.hanhan.test1.dto.AspnetMembers;
import com.hanhan.test1.dto.AspnetMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AspnetMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int countByExample(AspnetMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int deleteByExample(AspnetMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int insert(AspnetMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int insertSelective(AspnetMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    List<AspnetMembers> selectByExample(AspnetMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    AspnetMembers selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") AspnetMembers record, @Param("example") AspnetMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int updateByExample(@Param("record") AspnetMembers record, @Param("example") AspnetMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int updateByPrimaryKeySelective(AspnetMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aspnet_Members
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    int updateByPrimaryKey(AspnetMembers record);
}