package com.hanhan.test1.dto;

import java.math.BigDecimal;
import java.util.Date;

public class AspnetMembers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.UserId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.ReferralUserId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer referraluserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.GradeId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.UserName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Password
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.PasswordSalt
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String passwordsalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.PasswordQuestion
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String passwordquestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.PasswordAnswer
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String passwordanswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.CreateDate
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Email
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.RealName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.IdentityCard
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String identitycard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Picture
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Gender
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.BirthDate
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.IsOpenBalance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Boolean isopenbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.TradePassword
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String tradepassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.TradePasswordSalt
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String tradepasswordsalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.OrderNumber
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Expenditure
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private BigDecimal expenditure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Points
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Balance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.RequestBalance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private BigDecimal requestbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.TopRegionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer topregionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.RegionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer regionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Address
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.CellPhone
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.QQ
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Wangwang
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String wangwang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.WeChat
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.SessionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.SessionEndTime
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Date sessionendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.EmailVerification
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Boolean emailverification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.CellPhoneVerification
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Boolean cellphoneverification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.RegisteredSource
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Integer registeredsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.IsQuickLogin
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Boolean isquicklogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.IsLogined
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Boolean islogined;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.Unionid
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.IsSubscribe
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Boolean issubscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.NickName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.TagIds
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private String tagids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aspnet_Members.IsSendAppCoupons
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    private Boolean issendappcoupons;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.UserId
     *
     * @return the value of aspnet_Members.UserId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.UserId
     *
     * @param userid the value for aspnet_Members.UserId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.ReferralUserId
     *
     * @return the value of aspnet_Members.ReferralUserId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getReferraluserid() {
        return referraluserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.ReferralUserId
     *
     * @param referraluserid the value for aspnet_Members.ReferralUserId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setReferraluserid(Integer referraluserid) {
        this.referraluserid = referraluserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.GradeId
     *
     * @return the value of aspnet_Members.GradeId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.GradeId
     *
     * @param gradeid the value for aspnet_Members.GradeId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.UserName
     *
     * @return the value of aspnet_Members.UserName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.UserName
     *
     * @param username the value for aspnet_Members.UserName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Password
     *
     * @return the value of aspnet_Members.Password
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Password
     *
     * @param password the value for aspnet_Members.Password
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.PasswordSalt
     *
     * @return the value of aspnet_Members.PasswordSalt
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getPasswordsalt() {
        return passwordsalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.PasswordSalt
     *
     * @param passwordsalt the value for aspnet_Members.PasswordSalt
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setPasswordsalt(String passwordsalt) {
        this.passwordsalt = passwordsalt == null ? null : passwordsalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.PasswordQuestion
     *
     * @return the value of aspnet_Members.PasswordQuestion
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getPasswordquestion() {
        return passwordquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.PasswordQuestion
     *
     * @param passwordquestion the value for aspnet_Members.PasswordQuestion
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setPasswordquestion(String passwordquestion) {
        this.passwordquestion = passwordquestion == null ? null : passwordquestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.PasswordAnswer
     *
     * @return the value of aspnet_Members.PasswordAnswer
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getPasswordanswer() {
        return passwordanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.PasswordAnswer
     *
     * @param passwordanswer the value for aspnet_Members.PasswordAnswer
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setPasswordanswer(String passwordanswer) {
        this.passwordanswer = passwordanswer == null ? null : passwordanswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.CreateDate
     *
     * @return the value of aspnet_Members.CreateDate
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.CreateDate
     *
     * @param createdate the value for aspnet_Members.CreateDate
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Email
     *
     * @return the value of aspnet_Members.Email
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Email
     *
     * @param email the value for aspnet_Members.Email
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.RealName
     *
     * @return the value of aspnet_Members.RealName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.RealName
     *
     * @param realname the value for aspnet_Members.RealName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.IdentityCard
     *
     * @return the value of aspnet_Members.IdentityCard
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getIdentitycard() {
        return identitycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.IdentityCard
     *
     * @param identitycard the value for aspnet_Members.IdentityCard
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setIdentitycard(String identitycard) {
        this.identitycard = identitycard == null ? null : identitycard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Picture
     *
     * @return the value of aspnet_Members.Picture
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Picture
     *
     * @param picture the value for aspnet_Members.Picture
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Gender
     *
     * @return the value of aspnet_Members.Gender
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Gender
     *
     * @param gender the value for aspnet_Members.Gender
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.BirthDate
     *
     * @return the value of aspnet_Members.BirthDate
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.BirthDate
     *
     * @param birthdate the value for aspnet_Members.BirthDate
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.IsOpenBalance
     *
     * @return the value of aspnet_Members.IsOpenBalance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Boolean getIsopenbalance() {
        return isopenbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.IsOpenBalance
     *
     * @param isopenbalance the value for aspnet_Members.IsOpenBalance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setIsopenbalance(Boolean isopenbalance) {
        this.isopenbalance = isopenbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.TradePassword
     *
     * @return the value of aspnet_Members.TradePassword
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getTradepassword() {
        return tradepassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.TradePassword
     *
     * @param tradepassword the value for aspnet_Members.TradePassword
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setTradepassword(String tradepassword) {
        this.tradepassword = tradepassword == null ? null : tradepassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.TradePasswordSalt
     *
     * @return the value of aspnet_Members.TradePasswordSalt
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getTradepasswordsalt() {
        return tradepasswordsalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.TradePasswordSalt
     *
     * @param tradepasswordsalt the value for aspnet_Members.TradePasswordSalt
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setTradepasswordsalt(String tradepasswordsalt) {
        this.tradepasswordsalt = tradepasswordsalt == null ? null : tradepasswordsalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.OrderNumber
     *
     * @return the value of aspnet_Members.OrderNumber
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.OrderNumber
     *
     * @param ordernumber the value for aspnet_Members.OrderNumber
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Expenditure
     *
     * @return the value of aspnet_Members.Expenditure
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public BigDecimal getExpenditure() {
        return expenditure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Expenditure
     *
     * @param expenditure the value for aspnet_Members.Expenditure
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setExpenditure(BigDecimal expenditure) {
        this.expenditure = expenditure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Points
     *
     * @return the value of aspnet_Members.Points
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Points
     *
     * @param points the value for aspnet_Members.Points
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Balance
     *
     * @return the value of aspnet_Members.Balance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Balance
     *
     * @param balance the value for aspnet_Members.Balance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.RequestBalance
     *
     * @return the value of aspnet_Members.RequestBalance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public BigDecimal getRequestbalance() {
        return requestbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.RequestBalance
     *
     * @param requestbalance the value for aspnet_Members.RequestBalance
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setRequestbalance(BigDecimal requestbalance) {
        this.requestbalance = requestbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.TopRegionId
     *
     * @return the value of aspnet_Members.TopRegionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getTopregionid() {
        return topregionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.TopRegionId
     *
     * @param topregionid the value for aspnet_Members.TopRegionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setTopregionid(Integer topregionid) {
        this.topregionid = topregionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.RegionId
     *
     * @return the value of aspnet_Members.RegionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getRegionid() {
        return regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.RegionId
     *
     * @param regionid the value for aspnet_Members.RegionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setRegionid(Integer regionid) {
        this.regionid = regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Address
     *
     * @return the value of aspnet_Members.Address
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Address
     *
     * @param address the value for aspnet_Members.Address
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.CellPhone
     *
     * @return the value of aspnet_Members.CellPhone
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.CellPhone
     *
     * @param cellphone the value for aspnet_Members.CellPhone
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.QQ
     *
     * @return the value of aspnet_Members.QQ
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.QQ
     *
     * @param qq the value for aspnet_Members.QQ
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Wangwang
     *
     * @return the value of aspnet_Members.Wangwang
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getWangwang() {
        return wangwang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Wangwang
     *
     * @param wangwang the value for aspnet_Members.Wangwang
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setWangwang(String wangwang) {
        this.wangwang = wangwang == null ? null : wangwang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.WeChat
     *
     * @return the value of aspnet_Members.WeChat
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.WeChat
     *
     * @param wechat the value for aspnet_Members.WeChat
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.SessionId
     *
     * @return the value of aspnet_Members.SessionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.SessionId
     *
     * @param sessionid the value for aspnet_Members.SessionId
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid == null ? null : sessionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.SessionEndTime
     *
     * @return the value of aspnet_Members.SessionEndTime
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Date getSessionendtime() {
        return sessionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.SessionEndTime
     *
     * @param sessionendtime the value for aspnet_Members.SessionEndTime
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setSessionendtime(Date sessionendtime) {
        this.sessionendtime = sessionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.EmailVerification
     *
     * @return the value of aspnet_Members.EmailVerification
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Boolean getEmailverification() {
        return emailverification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.EmailVerification
     *
     * @param emailverification the value for aspnet_Members.EmailVerification
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setEmailverification(Boolean emailverification) {
        this.emailverification = emailverification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.CellPhoneVerification
     *
     * @return the value of aspnet_Members.CellPhoneVerification
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Boolean getCellphoneverification() {
        return cellphoneverification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.CellPhoneVerification
     *
     * @param cellphoneverification the value for aspnet_Members.CellPhoneVerification
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setCellphoneverification(Boolean cellphoneverification) {
        this.cellphoneverification = cellphoneverification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.RegisteredSource
     *
     * @return the value of aspnet_Members.RegisteredSource
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Integer getRegisteredsource() {
        return registeredsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.RegisteredSource
     *
     * @param registeredsource the value for aspnet_Members.RegisteredSource
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setRegisteredsource(Integer registeredsource) {
        this.registeredsource = registeredsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.IsQuickLogin
     *
     * @return the value of aspnet_Members.IsQuickLogin
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Boolean getIsquicklogin() {
        return isquicklogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.IsQuickLogin
     *
     * @param isquicklogin the value for aspnet_Members.IsQuickLogin
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setIsquicklogin(Boolean isquicklogin) {
        this.isquicklogin = isquicklogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.IsLogined
     *
     * @return the value of aspnet_Members.IsLogined
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Boolean getIslogined() {
        return islogined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.IsLogined
     *
     * @param islogined the value for aspnet_Members.IsLogined
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setIslogined(Boolean islogined) {
        this.islogined = islogined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.Unionid
     *
     * @return the value of aspnet_Members.Unionid
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.Unionid
     *
     * @param unionid the value for aspnet_Members.Unionid
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.IsSubscribe
     *
     * @return the value of aspnet_Members.IsSubscribe
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Boolean getIssubscribe() {
        return issubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.IsSubscribe
     *
     * @param issubscribe the value for aspnet_Members.IsSubscribe
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setIssubscribe(Boolean issubscribe) {
        this.issubscribe = issubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.NickName
     *
     * @return the value of aspnet_Members.NickName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.NickName
     *
     * @param nickname the value for aspnet_Members.NickName
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.TagIds
     *
     * @return the value of aspnet_Members.TagIds
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public String getTagids() {
        return tagids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.TagIds
     *
     * @param tagids the value for aspnet_Members.TagIds
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setTagids(String tagids) {
        this.tagids = tagids == null ? null : tagids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aspnet_Members.IsSendAppCoupons
     *
     * @return the value of aspnet_Members.IsSendAppCoupons
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public Boolean getIssendappcoupons() {
        return issendappcoupons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aspnet_Members.IsSendAppCoupons
     *
     * @param issendappcoupons the value for aspnet_Members.IsSendAppCoupons
     *
     * @mbggenerated Sun Jul 16 18:50:20 CST 2017
     */
    public void setIssendappcoupons(Boolean issendappcoupons) {
        this.issendappcoupons = issendappcoupons;
    }
}